modLoader = "javafml"
loaderVersion = "[33,)"
issueTrackerURL = "https://www.curseforge.com/minecraft/mc-mods/bundles-plus/" #optional
logoFile = "icon.png"
authors = "adoxentor,JimiIT92"
license = "Apache-2.0"
[[mods]]
modId = "bundlesplus"
version = "${version}"
displayName = "Bundles Plus"
description = '''
Bundles Plus
'''

[[dependencies.bundlesplus]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.10.13,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bundlesplus]]
modId = "architectury"
mandatory = true
versionRange = "[1.5.112,)"
ordering = "NONE"
side = "CLIENT"